### ISSUE TITLE
[Bug] Tracked quests show wrong number of items required

### ISSUE THREAD

**Issue by LUCIDLOVEBUG** [ScottyFox/AtlyssModTesting#2]
When there are some of the same type of item both in Spike storage and in the inventory, the quest tracker won't know the proper number of total materials owned and the numbers may glitch between higher and lower values, showing green as complete or turning back white as incomplete. This issue only occurs if the item is split between storage and inventory and does not occur if all of the owned stacks are placed into the inventory or all into Spike. It seems to be only a visual bug that doesn't cause loss of any items.

Image Description: The quest tracker displaying 10/15 mekboar spears, then 15/15 and turning green, and two pictures of the character inventory and storage showing that the actual total number of mekboar spears is 9

![Screenshot_1](https://github.com/user-attachments/assets/311d46b9-af8d-4787-bbf9-c6fa87396e8f)
![Screenshot_2](https://github.com/user-attachments/assets/666c5124-d0da-4e96-b33c-dd9ed0ab101e)
![Screenshot_3](https://github.com/user-attachments/assets/f1f64a0b-ea49-4076-ad37-315fa3a0633b)
![Screenshot_4](https://github.com/user-attachments/assets/56128327-5b80-45d0-b8c3-6fca4ae0c280)

**Comment by ScottyFox** [comment]
I found the issue, It would happen during a Quest Completion Check, where if you were to kill a creep it would check the quest progress. The problem is the number is modified to add the items inside spike, it unfortunately isn't reset to base-game count when a creep calls this check. I'll add in a manual player item-count check here instead. Thanks!

**Comment by ScottyFox** [comment]
One Additional Thing I did notice, was the on-screen tracking number not showing the correct number, i'll have to check what function does this. Otherwise, the quest item count should be correct. I'll fix this before uploading to thunder store.

![Screenshot 2024-12-10 151840](https://github.com/user-attachments/assets/f2b0cf37-de2a-429a-8271-bf603abfccb1)

**Comment by ScottyFox** [comment]
For now I am just grabbing the text that displays, there are a few checks in the base game that prevents you from being spammed from quest item progress. Just for now I'm just going to modify the text directly, and work on something more reliable later. What do you think? Should I included a (*) to indicate it's pulling from account storage?
![Screenshot 2024-12-10 155452](https://github.com/user-attachments/assets/395d1db3-d782-4116-8a0f-4c3dbf4d5b30)

**Comment by LUCIDLOVEBUG** [comment]
I think that works fine for now, probably put somewhere in the mod description that is what the asterisk means

**Comment by ScottyFox** [comment]
Thanks for the bug report, If you have any suggestions or have any more issues feel free to use the Issues Tab. First time using this feature on github. very interesting.
